'use strict';
const $=id=>document.getElementById(id),base=new URL('./',location.href),key='sidecar-mobile-v1';
let threads=[],thread=null,mode='list',files=[],sending=false,draftId=null,renderKey='',recorder=null,stream=null,authenticated=false;
const drafts=new Map();
function notice(message){$('notice').textContent=message;$('notice').hidden=!message;}
function cache(name,value){try{localStorage.setItem(key+name,JSON.stringify(value));}catch{}}
function cached(name,fallback){try{return JSON.parse(localStorage.getItem(key+name))??fallback;}catch{return fallback;}}
async function api(path,options={}) {const response=await fetch(new URL(path,base),{...options,headers:{'Content-Type':'application/json',...options.headers},credentials:'same-origin',cache:'no-store'});const data=await response.json();if(!response.ok){if(response.status===401&&path!=='api/pair')showPair();throw Error(data.error??'连接失败');}return data;}
function node(tag,text,className){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(className)e.className=className;return e;}
function showPair(){authenticated=false;for(const id of ['list','chat','ideas','composer','back','inbox','logout'])$(id).hidden=true;$('pair').hidden=false;$('title').textContent='随行';}
function setOnline(data){$('connection').textContent=data.online?'桌面在线 · 同一个对话':data.lastSeen?'桌面离线 · 可查看缓存，消息会等待上线':'正在等待桌面连接';}
function drawThreads(){const filter=$('filter').value.toLowerCase(),box=$('threads');box.replaceChildren();for(const item of threads.filter(t=>t.title.toLowerCase().includes(filter))){const b=node('button',undefined,'thread');b.append(node('strong',item.title||'未命名对话'),node('small',(item.status==='active'?'进行中 · ':'')+new Date(item.updatedAt*1000).toLocaleString('zh-CN')));b.onclick=()=>openThread(item);box.append(b);}$('count').textContent=threads.length+' 个对话';if(!threads.length)box.append(node('p','桌面首次同步后，你的对话会出现在这里。','intro'));}
function preserveDraft(){if(mode==='chat'||mode==='ideas')drafts.set(mode==='ideas'?'ideas':thread?.id,{text:$('input').value,files:[...files],draftId});}
function view(next,preserve=true){if(preserve)preserveDraft();mode=next;for(const id of ['pair','list','chat','ideas'])$(id).hidden=id!==next;$('back').hidden=next==='list';$('inbox').hidden=false;$('logout').hidden=false;$('composer').hidden=next!=='chat'&&next!=='ideas';$('record').hidden=next!=='ideas';$('title').textContent=next==='chat'?thread.title:'随行';$('send').textContent=next==='ideas'?'保存':'发送';const saved=drafts.get(next==='ideas'?'ideas':thread?.id);$('input').value=saved?.text??'';files=saved?.files??[];draftId=saved?.draftId??null;drawFiles();notice('');renderKey='';}
function openThread(item){preserveDraft();thread=item;view('chat',false);drawMessages(cached('read:'+thread.id,null));refreshRead().catch(e=>notice(e.message));}
function drawMessages(data){if(!data)return;const encoded=JSON.stringify([data.messages,data.cursor]);if(encoded===renderKey)return;const initial=!renderKey;renderKey=encoded;const box=$('messages'),nearBottom=initial||document.documentElement.scrollHeight-innerHeight-scrollY<250;box.replaceChildren();for(const message of data.messages){const article=node('article',undefined,'message '+message.role);article.dataset.messageId=message.id;article.append(node('small',message.role==='user'?'你':'CODEX'));const content=node('div',undefined,'message-content');if(message.role==='assistant')content.append(window.sidecarMarkdown(message.text));else content.textContent=message.text;article.append(content);box.append(article);}$('older').hidden=!data.cursor;$('older').dataset.cursor=data.cursor??'';if(nearBottom)scrollTo({top:document.documentElement.scrollHeight,behavior:'instant'});}
async function refreshRead(cursor){if(!thread||mode!=='chat'||!authenticated)return;const id=thread.id;const result=await api('api/read?threadId='+encodeURIComponent(id)+(cursor?'&cursor='+encodeURIComponent(cursor):''));if(thread?.id!==id)return;if(result.messages.length){cache('read:'+id,result);drawMessages(result);}setOnline(result);}
async function refreshThreads(){const data=await api('api/threads');authenticated=true;threads=data.threads;cache('threads',data);if(mode==='list')drawThreads();setOnline(data);$('inbox').hidden=$('logout').hidden=false;return data;}
const statusLabel={queued:'等待桌面接收',dispatching:'正在交给 Codex',delivered:'已送达',unknown:'结果未知 · 请核对原对话',failed:'未送达'};
async function refreshCommands(){const data=await api('api/commands');const box=$('commands');box.replaceChildren();for(const item of [...data.commands].reverse()){const card=node('article',undefined,'command');card.append(node('small',(item.kind==='idea'?'随手记 · ':'消息 · ')+statusLabel[item.status]),node('p',item.text||'附件'),node('small',item.error||new Date(item.createdAt).toLocaleString('zh-CN')));box.append(card);}if(!data.commands.length)box.append(node('p','还没有随手记。','intro'));}
$('pair-form').onsubmit=async e=>{e.preventDefault();try{await api('api/pair',{method:'POST',body:JSON.stringify({code:$('code').value})});authenticated=true;$('code').value='';view('list');await refreshThreads();}catch(error){notice(error.message);}};
$('filter').oninput=drawThreads;$('back').onclick=()=>{view('list');drawThreads();};$('inbox').onclick=()=>{view('ideas');refreshCommands().catch(e=>notice(e.message));};$('older').onclick=()=>refreshRead($('older').dataset.cursor).catch(e=>notice(e.message));
$('logout').onclick=async()=>{try{await api('api/logout',{method:'POST',body:'{}'});}finally{for(const k of Object.keys(localStorage))if(k.startsWith(key))localStorage.removeItem(k);drafts.clear();files=[];$('input').value='';stopRecording();showPair();}};
function drawFiles(){const box=$('attachments');box.replaceChildren();files.forEach((file,index)=>{const b=node('button',file.name+' ×','attachment');b.type='button';b.onclick=()=>{files.splice(index,1);draftId=null;drawFiles();};box.append(b);});}
async function addFile(file){if(files.length>=3)throw Error('最多添加 3 个附件');if(file.size>5*1024*1024)throw Error('附件请小于 5 MB');const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=()=>reject(Error('读取附件失败'));reader.readAsDataURL(file);});if(files.reduce((s,f)=>s+f.data.length,0)+data.length>7*1024*1024)throw Error('附件合计请小于 5 MB');files.push({name:file.name,mime:file.type.split(';')[0],data});draftId=null;drawFiles();}
$('file').onchange=async()=>{try{for(const file of $('file').files)await addFile(file);}catch(e){notice(e.message);}finally{$('file').value='';}};
function stopRecording(){if(recorder?.state==='recording')recorder.stop();stream?.getTracks().forEach(t=>t.stop());$('record').textContent='录音';}
$('record').onclick=async()=>{if(recorder?.state==='recording'){stopRecording();return;}try{stream=await navigator.mediaDevices.getUserMedia({audio:true});const mime=['audio/mp4','audio/webm','audio/ogg'].find(t=>MediaRecorder.isTypeSupported(t));recorder=new MediaRecorder(stream,mime?{mimeType:mime}:undefined);const activeRecorder=recorder,activeStream=stream;const chunks=[];let size=0;recorder.ondataavailable=e=>{chunks.push(e.data);size+=e.data.size;if(size>4*1024*1024)stopRecording();};recorder.onstop=async()=>{try{await addFile(new File(chunks,'随手录音.'+(activeRecorder.mimeType.includes('mp4')?'m4a':'webm'),{type:activeRecorder.mimeType}));}catch(e){notice(e.message);}finally{activeStream?.getTracks().forEach(t=>t.stop());}};recorder.start(1000);$('record').textContent='停止录音';notice('再次点击停止录音。录音作为附件保存，不会自动发送。');}catch{notice('无法打开麦克风。也可以使用键盘自带的语音输入。');}};
$('input').oninput=()=>{draftId=null;};
$('composer').onsubmit=async e=>{e.preventDefault();if(sending||(!$('input').value.trim()&&!files.length))return;sending=true;$('send').disabled=true;draftId??=crypto.randomUUID();const id=draftId;const payload={id,kind:mode==='ideas'?'idea':'send',...(mode==='chat'?{threadId:thread.id}:{}),text:$('input').value,attachments:[...files]};const draftKey=mode==='ideas'?'ideas':thread.id;preserveDraft();try{await api('api/send',{method:'POST',body:JSON.stringify(payload)});const currentKey=mode==='ideas'?'ideas':thread?.id;if(drafts.get(draftKey)?.draftId===id)drafts.delete(draftKey);if(currentKey===draftKey&&draftId===id){$('input').value='';files=[];draftId=null;drawFiles();}notice('已排队，送达状态可在随手记里查看。');if(mode==='ideas')await refreshCommands();}catch(error){notice(error.message+'。原文已保留；重试会使用同一消息编号。');}finally{sending=false;$('send').disabled=false;}};
window.addEventListener('pagehide',stopRecording);
window.addEventListener('online',()=>refreshThreads().catch(()=>{}));
const code=new URLSearchParams(location.hash.slice(1)).get('pair');if(code){$('code').value=code;history.replaceState(null,'',location.pathname);}
refreshThreads().then(()=>{view('list');drawThreads();}).catch(()=>{const saved=cached('threads',null);if(!navigator.onLine&&saved){threads=saved.threads;view('list');drawThreads();$('connection').textContent='网络离线 · 仅显示这台手机的缓存';}else showPair();});
setInterval(()=>{if(!authenticated||document.hidden)return;if(mode==='chat')refreshRead().catch(()=>{});else if(mode==='ideas')refreshCommands().catch(()=>{});else refreshThreads().catch(()=>{});},3500);
if('serviceWorker'in navigator)navigator.serviceWorker.register(new URL('sw.js',base),{scope:base.pathname}).catch(()=>{});
