import {element,button} from './components.js';
import {remaining,timerDone,timerLabel,type StudyTimer,type TimerCommand} from '../shared/timer.js';

export function createStudyTimer(win:Window,send:(command:TimerCommand)=>Promise<unknown>,open:()=>void){
 const doc=win.document,root=element(doc,'div','study-timer'),style=element(doc,'style');
 style.textContent=`
.study-timer{display:flex;flex-direction:column;gap:18px}.timer-current{padding:23px 18px;border:1px solid #dcd1e3;border-radius:22px;background:linear-gradient(140deg,#f2ebf6,#fffdf8);text-align:center}.timer-kicker{font-size:12px;color:#75637e;margin:0 0 10px}.timer-title{font-size:18px;line-height:1.5;overflow-wrap:anywhere;margin:0}.timer-clock{font:500 54px/1.35 "Cascadia Mono",monospace;font-variant-numeric:tabular-nums;letter-spacing:-2px;color:#493057;margin:9px 0}.timer-progress{width:100%;height:6px;accent-color:#765389;border:0;border-radius:5px;overflow:hidden;appearance:none}.timer-progress::-webkit-progress-bar{background:#e7deeb;border-radius:5px}.timer-progress::-webkit-progress-value{background:#765389;border-radius:5px}.timer-controls{display:flex;justify-content:center;flex-wrap:wrap;gap:8px;margin-top:16px}.timer-help{font-size:12px;color:#75637e;line-height:1.65;margin:10px 0 0}.timer-plan{display:flex;flex-direction:column;gap:8px}.timer-row{display:flex;align-items:center;gap:8px;padding:12px;border:1px solid #e3dbe8;border-radius:14px;background:#fffdfb}.timer-row-copy{flex:1;min-width:0;overflow-wrap:anywhere}.timer-row-copy strong{display:block;font-size:13px;font-weight:500}.timer-row-copy small{color:#75637e}.timer-row button{padding:6px;font-size:12px}.timer-form{display:flex;flex-direction:column;gap:10px}.timer-form input,.timer-form select{min-width:0;padding:10px;border:1px solid #d3c5dc;border-radius:12px;background:#fffdfb;color:#493057;font:inherit}.timer-form label{display:flex;flex-direction:column;gap:5px;font-size:12px;color:#75637e}.timer-fields{display:grid;grid-template-columns:1fr 1fr;gap:10px}.timer-presets{display:flex;flex-wrap:wrap;gap:6px}.timer-presets button{font-size:12px;padding:6px 9px}.timer-status{color:#8c472f;font-size:12px;line-height:1.6}.timer-badge{visibility:visible;position:fixed;right:24px;bottom:82px;max-width:min(300px,calc(100vw - 40px));white-space:nowrap;overflow:hidden;text-overflow:ellipsis;pointer-events:auto;padding:10px 15px;border:1px solid #cdbed3;border-radius:18px;background:#faf6fc;box-shadow:0 4px 18px #34204418;color:#493057;font:13px "HarmonyOS Sans SC",sans-serif}.timer-badge[data-done=true]{background:#fbf1d9;border-color:#c1a16b;color:#624820}.timer-heading{font-size:14px;font-weight:600;margin:0}.timer-sound{display:flex;align-items:center;gap:8px;font-size:12px;color:#75637e}.timer-sound input{accent-color:#765389}
`;
 root.append(style);
 const badge=button(doc,'','study-timer-badge',undefined,'timer-badge');badge.hidden=true;badge.onclick=open;
 const current=element(doc,'section','timer-current'),kicker=element(doc,'p','timer-kicker'),title=element(doc,'h2','timer-title'),clock=element(doc,'div','timer-clock','25:00'),progress=element(doc,'progress','timer-progress'),controls=element(doc,'div','timer-controls'),help=element(doc,'p','timer-help');
 clock.setAttribute('aria-label','剩余时间');clock.setAttribute('aria-live','off');progress.max=1;progress.setAttribute('aria-label','当前学习块进度');
 current.append(kicker,title,clock,progress,controls,help);
 const status=element(doc,'p','timer-status');status.hidden=true;status.setAttribute('role','status');
 const queue=element(doc,'div','timer-plan'),heading=element(doc,'h3','timer-heading','接下来的安排'),form=element(doc,'form','timer-form');
 const titleLabel=element(doc,'label','', '这一块准备做什么'),input=element(doc,'input');input.placeholder='例如：理解交叉验证';input.maxLength=120;input.required=true;input.setAttribute('aria-label','学习块名称');titleLabel.append(input);
 const fields=element(doc,'div','timer-fields'),minutesLabel=element(doc,'label','','分钟'),minutes=element(doc,'input');minutes.type='number';minutes.min='1';minutes.max='180';minutes.step='1';minutes.value='25';minutes.required=true;minutes.setAttribute('aria-label','学习块分钟');minutesLabel.append(minutes);
 const kindLabel=element(doc,'label','','类型'),kind=element(doc,'select');kind.setAttribute('aria-label','学习块类型');for(const [value,text]of [['study','学习 / 做事'],['break','休息']]){const o=element(doc,'option','',text);o.value=value!;kind.append(o);}kindLabel.append(kind);fields.append(minutesLabel,kindLabel);
 const presets=element(doc,'div','timer-presets');for(const count of [15,25,45,60]){const b=button(doc,count+' 分钟','timer-preset-'+count);b.onclick=()=>{minutes.value=String(count);kind.value='study';};presets.append(b);}const rest=button(doc,'休息 5 分钟','timer-preset-break');rest.onclick=()=>{minutes.value='5';kind.value='break';if(!input.value.trim())input.value='休息一下';};presets.append(rest);
 const add=button(doc,'＋ 加入安排','timer-add');add.type='submit';form.append(titleLabel,fields,presets,add);
 const soundLabel=element(doc,'label','timer-sound'),sound=element(doc,'input');sound.type='checkbox';sound.checked=true;try{sound.checked=win.localStorage.getItem('codex-sidecar.timer-sound')!=='off';}catch{}soundLabel.append(sound,doc.createTextNode('到点轻提示音'));sound.onchange=()=>{try{win.localStorage.setItem('codex-sidecar.timer-sound',sound.checked?'on':'off');}catch{}if(sound.checked)armAudio();};
 root.append(current,status,heading,queue,form,soundLabel,element(doc,'p','timer-help','到点会保留提示，不会自动开始下一块。Sidecar 运行时提醒；重新打开后会按实际时间恢复。'));
 let state:StudyTimer={queue:[],current:null},busy=false,disposed=false,signature='',lastDone='',audio:AudioContext|undefined;
 function armAudio(){if(!sound.checked)return;try{const Constructor=(win as any).AudioContext;if(Constructor){audio??=new Constructor();void audio?.resume().catch(()=>{});}}catch{}}
 function chime(){if(!sound.checked||audio?.state!=='running')return;try{for(let i=0;i<2;i++){const o=audio.createOscillator(),g=audio.createGain(),at=audio.currentTime+i*.24;o.frequency.value=i?784:659;g.gain.setValueAtTime(0,at);g.gain.linearRampToValueAtTime(.07,at+.025);g.gain.exponentialRampToValueAtTime(.001,at+.2);o.connect(g);g.connect(audio.destination);o.start(at);o.stop(at+.22);}}catch{}}
 async function run(command:TimerCommand){if(busy)return false;busy=true;status.hidden=true;draw();try{await send(command);if(command.op==='start'&&root.parentElement)root.parentElement.scrollTop=0;return true;}catch(e){status.textContent=e instanceof Error?e.message:String(e);status.hidden=false;return false;}finally{busy=false;if(!disposed)draw();}}
 const commandButton=(label:string,op:TimerCommand['op'])=>{const b=button(doc,label,'timer-'+op);b.disabled=busy;b.onclick=()=>{armAudio();void run({op} as TimerCommand);};return b;};
 form.onsubmit=e=>{e.preventDefault();const text=input.value.trim(),duration=Number(minutes.value);if(!text||!Number.isInteger(duration)||duration<1||duration>180){status.textContent='填写一个学习块名称，以及 1–180 分钟的时长。';status.hidden=false;return;}armAudio();void run({op:'add',title:text,minutes:duration,kind:kind.value as 'study'|'break'}).then(ok=>{if(ok&&input.value.trim()===text)input.value='';});};
 function draw(){
  const c=state.current,done=timerDone(c);controls.replaceChildren();add.disabled=busy;
  if(!c){kicker.textContent='一次，只照顾一件事';title.textContent=state.queue[0]?.title??'给下一件事留一段时间';clock.textContent=timerLabel((state.queue[0]?.minutes??25)*60_000);progress.value=0;help.textContent='把其他事情放进安排里，先安心做当前这一块。';if(state.queue.length)controls.append(commandButton('开始第一块','start'));}
  else{kicker.textContent=done?'这一块到时间了':c.status==='paused'?'已暂停':c.kind==='break'?'现在，休息一下':'这段时间，只做这一件事';title.textContent=c.title;help.textContent=done?'可以歇一歇，再决定是否继续。':c.status==='paused'?'准备好了再继续。':'其他安排已经记下，不需要现在一起做。';if(done){if(state.queue.length)controls.append(commandButton('开始下一块','start'));controls.append(commandButton('收好这次计时','dismiss'));}else{controls.append(commandButton(c.status==='paused'?'继续':'暂停',c.status==='paused'?'start':'pause'),commandButton('提前结束','finish'));}}
  queue.replaceChildren();heading.textContent=`接下来的安排 · ${state.queue.length} 块 · ${state.queue.reduce((n,b)=>n+b.minutes,0)} 分钟`;
  if(!state.queue.length)queue.append(element(doc,'p','timer-help','把接下来想做的事放在这里，每一块都可以单独设时间。'));
  state.queue.forEach((block,index)=>{const row=element(doc,'div','timer-row'),copy=element(doc,'div','timer-row-copy');copy.append(element(doc,'strong','',block.title),element(doc,'small','',`${block.kind==='break'?'休息':'学习'} · ${block.minutes} 分钟`));row.append(copy);if(index){const up=button(doc,'上移','timer-up');up.disabled=busy;up.onclick=()=>void run({op:'up',id:block.id});row.append(up);}const remove=button(doc,'删除','timer-remove');remove.disabled=busy;remove.setAttribute('aria-label','删除学习块：'+block.title);remove.onclick=()=>void run({op:'remove',id:block.id});row.append(remove);queue.append(row);});tick();
 }
 function tick(){const c=state.current;if(!c){badge.hidden=true;return;}const ms=remaining(c),done=timerDone(c);clock.textContent=timerLabel(ms);progress.value=1-ms/(c.minutes*60_000);badge.hidden=false;badge.dataset.done=String(done);badge.textContent=(done?'时间到':c.status==='paused'?'已暂停 · '+timerLabel(ms):timerLabel(ms))+' · '+c.title;badge.title=badge.textContent+' · 打开学习计时';
  const token=c.id+':'+c.endsAt;
  if(done&&lastDone!==token){lastDone=token;draw();status.textContent=`「${c.title}」已到时间。准备好后再开始下一块。`;status.hidden=false;}
  if(done&&doc.visibilityState==='visible'&&sound.checked&&audio?.state==='running'){try{const key='codex-sidecar.timer-chime';if(win.localStorage.getItem(key)!==token){win.localStorage.setItem(key,token);chime();}}catch{chime();}}
 }
 const interval=win.setInterval(tick,500);draw();
 return {element:root,style,badge,receive(timer?:StudyTimer){state=timer??{queue:[],current:null};const next=JSON.stringify(state);if(signature!==next){signature=next;draw();}},destroy(){disposed=true;win.clearInterval(interval);void audio?.close().catch(()=>{});root.remove();style.remove();badge.remove();}};
}
